// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtghuxpgomoobwdmncno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0Z2h1eHBnb21vb2J3ZG1uY25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDYzMTIsImV4cCI6MjA3MjA4MjMxMn0.AJcUfdMHQJn55kqNzHuWNjmzQnBNgCRLeiurnPFRS_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});